MODEL:
  BACKBONE: ssl_swinunetr
  PRETRAINED: None
  DIR: /data/mskacquisition/TBRecon/model_saved
  SAVE_NAME: swinunetr_all_ssl_bs2_softmax_crop96_snorm0.5_df_ep800.pt
  USE_LOAD_EPOCH: False
  ROI: [96, 96, 96]
  NUM_SAMPLES: 2
  NUM_CLASSES: 7
  SW_BATCH_SIZE: 4
  INFER_OVERLAP: 0.7
  CLIP_GRAD: 1.0
DATA:
  BASE_PATH: /data/mskacquisition/TBRecon_data
  TRAIN_CSV_PATH: /data/mskacquisition/TBRecon/dataset/SSL/train_ssl.csv
  VAL_CSV_PATH: /data/mskacquisition/TBRecon/dataset/SSL/val_ssl.csv
  TEST_CSV_PATH: /data/mskacquisition/TBRecon/dataset/SSL/test_ssl.csv
  NUM_WORKERS: 4
  CACHE_DIR: /data/mskacquisition/TBRecon_data/TBRecon_cache_dir_ssl
  CACHE_RATE: 1.0
  CROP_RATE: 1.0
TRAIN:
  MAX_EPOCHS: 800
  WARMUP_EPOCHS: 20
  VAL_EVERY: 1
  BASE_LR: 1.0e-4
  MIN_LR: 1.0e-8
  WEIGHT_DECAY: 1.0e-5
  LOSS: dice_focal
WANDB:
  WANDB_ENABLE: False
  PROJECT: swinunetr_all_ssl_bs2_softmax_crop96_snorm0.5_df_ep800_dgx
LOG:
  FILENAME: swinunetr_all_ssl_bs2_softmax_crop96_snorm0.5_df_ep800_dgx
MODE: 'ssl_pretrain'
SEED: 3074
OUTPUT: /data/mskacquisition/TBRecon/configs/ssl/json
